create table kiss_full_2013_10_16 (
    dt string,
    `_n` string,
    `_p` string,
    `_p2` string,
    `_t` string,
    `add_to_cart_category_id` string,
    `add_to_cart_category_name` string,
    `add_to_cart_f1_quantity` string,
    `add_to_cart_page_url` string,
    `add_to_cart_product_name` string,
    `add_to_cart_root_category` string,
    `add_to_cart_root_id` string,
    `add_to_cart_sku` string,
    `add_to_cart_sku_price` string,
    `add_to_cart_sku_quantity` string,
    `banner_id` string,
    `banner_url` string,
    `campaign_content` string,
    `campaign_medium` string,
    `campaign_name` string,
    `campaign_source` string,
    `campaign_terms` string,
    `category_results_clicked_category_id` string,
    `category_results_clicked_category_level` string,
    `category_results_clicked_category_name` string,
    `category_results_clicked_category_type` string,
    `category_results_clicked_page_number` string,
    `category_results_clicked_parent_category` string,
    `category_results_clicked_product_name` string,
    `category_results_clicked_product_position` string,
    `category_results_clicked_sku` string,
    `center_image_url` string,
    `checkout_complete_category_name` string,
    `checkout_complete_delivery` string,
    `checkout_complete_delivery_total` string,
    `checkout_complete_order_id` string,
    `checkout_complete_order_total` string,
    `checkout_complete_order_type` string,
    `checkout_complete_parent_category` string,
    `checkout_complete_payment` string,
    `checkout_complete_sku` string,
    `checkout_complete_sku_price` string,
    `checkout_complete_sku_quantity` string,
    `checkout_complete_sku_total` string,
    `checkout_step_1_order_total` string,
    `checkout_step_1_order_type` string,
    `checkout_step_1_sku_quantity` string,
    `checkout_step_1_sku_total` string,
    `informer` string,
    `optimizely_filters` string,
    `referrer` string,
    `returning` string,
    `search_engine` string,
    `search_items_found` string,
    `search_page_url` string,
    `search_string` string,
    `search_terms` string,
    `url` string,
    `view_cart_sku_quantity` string,
    `view_cart_sku_total` string,
    `viewed_category_category_id` string,
    `viewed_category_category_level` string,
    `viewed_category_category_name` string,
    `viewed_category_category_type` string,
    `viewed_category_parent_category` string,
    `viewed_product_product_name` string,
    `viewed_product_product_status` string,
    `viewed_product_sku` string
)
stored as rcfile
location 's3://enter-kiss-test/enter_proto_full_2013_10_16/kiss_full_2013_10_16/';


create table session_pairs_full_2013_10_16(
  p string, 
  p2 string)
location 's3://enter-kiss-test/enter_proto_full_2013_10_16/session_pairs/';


create external table session_alias_full_2013_10_16 (
    session string, 
    alias string) 
location 's3://enter-kiss-test/enter_proto_full_2013_10_16/sessions/';
